# Generated by Django 4.2 on 2026-02-14 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostAndFound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=100)),
                ('item_status', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=10)),
                ('description', models.TextField()),
                ('location', models.CharField(help_text='Where the item was found/lost', max_length=200)),
                ('date_found_lost', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='lost_found/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('returned', 'Returned')], default='open', max_length=20)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('claim_date', models.DateTimeField(blank=True, null=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_items', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lost & Found Item',
                'verbose_name_plural': 'Lost & Found Items',
                'ordering': ['-report_date'],
            },
        ),
    ]
